### ISSUE TITLE
Get variables into Show Blade

### ISSUE THREAD

**Issue by bciar** [iainfelix/PeasyPOC#1]
Description...

**Comment by iainfelix** [comment]
Need to get supplier company_name/email and customer company_name/email in Show Blade

        <div class="row">
                <div class="col-sm-2"><b>Supplier:</b> </div><div class="col-sm-2"><?php echo e**($supplier->company_name)**; ?></div> 
        </div>
        <div class="row">
                <div class="col-sm-2"><b>Supplier Email:</b></div><div class="col-sm-2"><?php echo e**($offer->supplier_email);** ?></div>
        </div>
        <div class="row">
                <div class="col-sm-2"><b>Customer:</b> </div><div class="col-sm-2"><?php echo e**($offer->supplier_email)**; ?></div> 
        </div>
        <div class="row">
                <div class="col-sm-2"><b>Customer Email:</b></div><div class="col-sm-2"><?php echo e**($offer->customer_email);** ?></div>
